services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: messenger
      POSTGRES_USER: messenger
      POSTGRES_DB: messenger
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  messenger:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres://messenger:messenger@db:5432/messenger?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
        - backend
  
networks:
  backend:
    driver: bridge
